---
# tasks file for apache

- name: Install Apache2
  package:
    name: "{{ apache_package }}"
    state: present
  tags: apache

- name: Start Apache2
  service:
    name: "{{ apache_package }}"
    state: started
  tags: apache

- name: Enable Apache2 at boot
  service:
    name: "{{ apache_package }}"
    enabled: yes
  tags: apache
